# Use Base Image playwright:bionic
FROM mcr.microsoft.com/playwright:v1.24.0-focal
USER root
WORKDIR /tests
COPY . .
# Install Playwright dependancies
RUN npm install
# # # Install dependencies.
RUN npx @playwright/test install
# # # Run Tests
RUN npx playwright test --reporter=html --config playwright.config.js