# Use Base Image playwright:bionic
FROM mcr.microsoft.com/playwright:v1.24.0-focal
USER root
WORKDIR /automation
COPY package.json ./
COPY package-lock.json ./
# Install Playwright dependancies
RUN npm install
COPY . ./
# Install dependencies.
RUN npx @playwright/test install

# Run Tests
RUN npx playwright test